### PR TITLE
fix: remove the stroke color from a Marker

### LINKED ISSUE #138: Stroke herited for shapes in Series marker

### PR DESCRIPTION
**Pull request by Sebastien-Ahkrin**
Fixes #138

### CODE REVIEW

File: src/components/ScatterSeries.tsx [hunk 1]
```diff
@@ -79,16 +79,16 @@ function ScatterSeriesRender({
...
       return (
         <g // eslint-disable-next-line react/no-array-index-key
           key={`markers-${i}`}
           transform={`translate(${xScale(point.x)}, ${yScale(point.y)})`}
         >
-          <Marker
-            size={markerSize}
-            style={functionalStyle(defaultColor, markerStyle, point, i, data)}
-          />
+          <Marker size={markerSize} style={{ ...style, stroke: style.fill }} />
```
Comment (maasencioh) [inline src/components/ScatterSeries.tsx:91]: For me, the order should be different, because the user rules should have more priority.

```suggestion
          <Marker size={markerSize} style={{ stroke: style.fill, ...style }} />
```

**Review by maasencioh — APPROVED** [review]
